[[libavif]]
arch = "aarch64"
git-tree-sha1 = "5f70f2df8ef294e953c1ce71146c8c3a7bd47819"
os = "macos"

    [[libavif.download]]
    sha256 = "cbc714a5b9fa4c4bb2d78bef5b9ad9015c375f3393fa3ed9f316c57cc5abe6a2"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.aarch64-apple-darwin.tar.gz"
[[libavif]]
arch = "aarch64"
git-tree-sha1 = "534108bd1f63b8fe546e983b7a9aaf3bdb48ba29"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "66f71f5913988d6a15cc7f067da23623cb0deb792eeaee54978c855fe005b541"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.aarch64-linux-gnu.tar.gz"
[[libavif]]
arch = "aarch64"
git-tree-sha1 = "7e57bd71995c0ccf2eeb54b9f839b772fb11655d"
libc = "musl"
os = "linux"

    [[libavif.download]]
    sha256 = "5f56c30a77af269a9e27121d836dcce43e602bf3a4554931867f87ea316ea754"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.aarch64-linux-musl.tar.gz"
[[libavif]]
arch = "aarch64"
git-tree-sha1 = "83f8027c7165710813bf5771d909ba39dd561f1b"
os = "freebsd"

    [[libavif.download]]
    sha256 = "83917930a8940f14509ba4fc42b796d91de290bd7a206f4b3eb467cbd35f44b3"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.aarch64-unknown-freebsd.tar.gz"
[[libavif]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ed208afc8445adb0819e1f02307eb830dc01ba6e"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "7fecc411621916a0c3beb72d26b8bdee0c7947840c59f93fecbc1bf8eb957a6d"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.armv6l-linux-gnueabihf.tar.gz"
[[libavif]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "158b7cedef289eb662abd48613ca67d3c3906bef"
libc = "musl"
os = "linux"

    [[libavif.download]]
    sha256 = "e4e69bc7b385c1b89b07cd3fbb177f9c01a23e3c8313204e4f0e5bac729ec24e"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.armv6l-linux-musleabihf.tar.gz"
[[libavif]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0cd044718798989d1f3cfdf94b0d09480c67cf27"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "df81a66e7ed0165ccfe9ff824261432544b156d7840879e6bdc5bd1b926d8dd6"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[libavif]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4926baff4b67e5449b27d2c44d294b0f1e4695b8"
libc = "musl"
os = "linux"

    [[libavif.download]]
    sha256 = "bdc3ba4add80b4650ee0cf5e079daccdc429671efc32b8b332dffd003cbfa684"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[libavif]]
arch = "i686"
git-tree-sha1 = "d99ef587be8caf0eca351170fd56f85befa49597"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "9d177d6c6a076c841d1cd41684e68f2c110553758cb720583aaa9cc1fdbac5ec"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.i686-linux-gnu.tar.gz"
[[libavif]]
arch = "i686"
git-tree-sha1 = "a2be4496ce54ee07104d53f0982a9f872fd9bbd8"
libc = "musl"
os = "linux"

    [[libavif.download]]
    sha256 = "e51d93e077d328ec2a977de627a66ac03f878962cb4a95bd90395e3a99325538"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.i686-linux-musl.tar.gz"
[[libavif]]
arch = "i686"
git-tree-sha1 = "a7fb345a708d26d907fd18c0f335b1385394a139"
os = "windows"

    [[libavif.download]]
    sha256 = "ebee579933fd81ec33c4548e62fd4068375ed7283678d43529965daa43655670"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.i686-w64-mingw32.tar.gz"
[[libavif]]
arch = "powerpc64le"
git-tree-sha1 = "8ad3e9347562f439b0380c6956fa4a83d1cb12a0"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "a91ee2aec712abfa03359207b3c016c18883768cbd4466261c9b1144ee744387"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[libavif]]
arch = "riscv64"
git-tree-sha1 = "e7f74487abe3e129000ef2ec6c2922514bfeda0a"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "03f1325c197d3402ec549992990435392bd94b4413a7398b0944945f6064ae38"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.riscv64-linux-gnu.tar.gz"
[[libavif]]
arch = "x86_64"
git-tree-sha1 = "6465b53d461c4d210150b7ad61f48b803ccdb4ab"
os = "macos"

    [[libavif.download]]
    sha256 = "f56f8a321ade56bf7c81372d8f16eaa111a3c5c94924afaea9b8f57d1678727d"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.x86_64-apple-darwin.tar.gz"
[[libavif]]
arch = "x86_64"
git-tree-sha1 = "3fb60a6016822be12db512c9e4da93ce007782a2"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "5a1445485d93f97fc226d69c2e5215ec181897cdbe0bb70c2401ddfe893c0ba3"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.x86_64-linux-gnu.tar.gz"
[[libavif]]
arch = "x86_64"
git-tree-sha1 = "6c7df31dd101d069381467a0245faa191110281b"
libc = "musl"
os = "linux"

    [[libavif.download]]
    sha256 = "c62f434f734bd97e53135a3073768135008721196c20198b18a59cc0a5226dab"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.x86_64-linux-musl.tar.gz"
[[libavif]]
arch = "x86_64"
git-tree-sha1 = "c88c80768c2abcd70f921f833fa27e5cdea4cf2d"
os = "freebsd"

    [[libavif.download]]
    sha256 = "8b761fffe99e2af26e2443f9d7e41ac8722f51799523430ad3673a3e2e35e809"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.x86_64-unknown-freebsd.tar.gz"
[[libavif]]
arch = "x86_64"
git-tree-sha1 = "8ac9f68bca13d25a7eab693f22c48bc2cba02bcb"
os = "windows"

    [[libavif.download]]
    sha256 = "2142eb16debc1a91f368259913af2bd242772e987633b2c5574e53534352b810"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.3.0+0/libavif.v1.3.0.x86_64-w64-mingw32.tar.gz"
