[[libavif]]
arch = "aarch64"
git-tree-sha1 = "bac6f114e2593ace94b84add53f7dafa107fc955"
os = "macos"

    [[libavif.download]]
    sha256 = "788975727e677e5d98803a2d2960b47414c023256b42008467d359cca094f133"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.aarch64-apple-darwin.tar.gz"
[[libavif]]
arch = "aarch64"
git-tree-sha1 = "8724fd47242cbe1b85de8e9a8328817ffca1cef6"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "abda9042ca529517c7d0be313a9438e5a4d629cccdeed39add59f0dc380f90d7"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.aarch64-linux-gnu.tar.gz"
[[libavif]]
arch = "aarch64"
git-tree-sha1 = "b5d82c345b2f90e3eb9b9386b6284dfd4feaa4af"
libc = "musl"
os = "linux"

    [[libavif.download]]
    sha256 = "1a87e88b88a768c77facd32f7712be09dcc384be002372848ee8c40aa9a0d13d"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.aarch64-linux-musl.tar.gz"
[[libavif]]
arch = "aarch64"
git-tree-sha1 = "b2dcecbaeae94560cc672da00793d5c295fcea3f"
os = "freebsd"

    [[libavif.download]]
    sha256 = "b5f79096017e144fa72c94de2fb73fd83042b4310b68296e05a22895189505b0"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.aarch64-unknown-freebsd.tar.gz"
[[libavif]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "809d81ce7316c4f2f0875ead1b0b815101197157"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "6f7496bc39460373dd270c04fc1e785cea137e999e89bb6d730167854f39766e"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.armv6l-linux-gnueabihf.tar.gz"
[[libavif]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d42c00f50ba139592ebed6f6d40e7de5efb4cce1"
libc = "musl"
os = "linux"

    [[libavif.download]]
    sha256 = "65b6bae9e824e437124ca74b4d542f1a2f7c734181beb24c84a8c7249d3972bf"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.armv6l-linux-musleabihf.tar.gz"
[[libavif]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "225e7ab7c1e2adc4f335c5b4a5b50564eb9294b3"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "75c0e0418183da1f1edeb8228a881c6add205714b9dc602ff0ce27762cfe2c92"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.armv7l-linux-gnueabihf.tar.gz"
[[libavif]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b5940d4c23f5d5aa7a45aa80b34d2a7e5edfbd3a"
libc = "musl"
os = "linux"

    [[libavif.download]]
    sha256 = "5687cd7a135c953124c53bb3cc73517532911610a4ed63c28ff469af7bf96e04"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.armv7l-linux-musleabihf.tar.gz"
[[libavif]]
arch = "i686"
git-tree-sha1 = "6db64632fc16cc9010a4d25a409d3d36cc7f99bd"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "783ab6bf49ce196e0f05d98b9572d92456d57ec30b19211e499b031232911dfc"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.i686-linux-gnu.tar.gz"
[[libavif]]
arch = "i686"
git-tree-sha1 = "220cf29228a475a76df1e6ddc505ddbe15c3162d"
libc = "musl"
os = "linux"

    [[libavif.download]]
    sha256 = "a067e37b4e49b118be7ba1a532e874b958b8f48d03e1a176738f06c9f2535381"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.i686-linux-musl.tar.gz"
[[libavif]]
arch = "i686"
git-tree-sha1 = "db12b039217ec13338e715a6529e2b7af7725b88"
os = "windows"

    [[libavif.download]]
    sha256 = "4f2bad72447e9fdd7106851aacda72acb4165fb612bbbfad5577391ccad15db7"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.i686-w64-mingw32.tar.gz"
[[libavif]]
arch = "powerpc64le"
git-tree-sha1 = "3c5aef38ea9cddd45cbbbf29dc0a45a5f1ccb6f3"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "e9dc8b5ffc4494a22f54ca45742fd7a114ddda8dc0a01709753e7372b458b3a5"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.powerpc64le-linux-gnu.tar.gz"
[[libavif]]
arch = "riscv64"
git-tree-sha1 = "5a3652b773609cf3f573fc5156eeef8e0a6df5a0"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "4ee14f9a2602705b8f8868a10af3a36a56664f960608566529534ed9d6bde53b"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.riscv64-linux-gnu.tar.gz"
[[libavif]]
arch = "x86_64"
git-tree-sha1 = "6f059ffb3e37d2d958fc83f624901124fd7af3fd"
os = "macos"

    [[libavif.download]]
    sha256 = "5091ea11e051930f62504c3d147ea70c40bc211eef4974735db0e8f18150fce2"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.x86_64-apple-darwin.tar.gz"
[[libavif]]
arch = "x86_64"
git-tree-sha1 = "759b0ad81bac28119ce662b086e31f405bd45c6b"
libc = "glibc"
os = "linux"

    [[libavif.download]]
    sha256 = "ad5c816148ca4680c22ab3093fcea639a20b892fd4b5312148b6f4432c664f45"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.x86_64-linux-gnu.tar.gz"
[[libavif]]
arch = "x86_64"
git-tree-sha1 = "f3a78f9fa56211a9d2e1461a0c960c4fea2ff314"
libc = "musl"
os = "linux"

    [[libavif.download]]
    sha256 = "6474da204146d0c4a1cadddb5a575de4c05031e138f4441644fd7e093d02a2a0"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.x86_64-linux-musl.tar.gz"
[[libavif]]
arch = "x86_64"
git-tree-sha1 = "e11d569400f743e155da3e2c6bc66303866c31c0"
os = "freebsd"

    [[libavif.download]]
    sha256 = "92a96d581a680fe8cd00660c4eafcb242df596a6237460f18616eed4d8ec6a2e"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.x86_64-unknown-freebsd.tar.gz"
[[libavif]]
arch = "x86_64"
git-tree-sha1 = "55c6d1893e67ec2226de3eb375e62c4499a238a5"
os = "windows"

    [[libavif.download]]
    sha256 = "d1ca6b07f0dd1ec59361e88e5be0cfe79bc8172c627fb4779764e38c2b450280"
    url = "https://github.com/JuliaBinaryWrappers/libavif_jll.jl/releases/download/libavif-v1.4.1+0/libavif.v1.4.1.x86_64-w64-mingw32.tar.gz"
